/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_qi1002_opencvdemo_JniActivity */

#ifndef _Included_io_github_qi1002_opencvdemo_JniActivity
#define _Included_io_github_qi1002_opencvdemo_JniActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_qi1002_opencvdemo_JniActivity
 * Method:    getEdge
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_io_github_qi1002_opencvdemo_JniActivity_getEdge
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
